basePath: /
definitions:
  models.Delivery:
    properties:
      address:
        maxLength: 100
        minLength: 10
        type: string
      city:
        maxLength: 50
        minLength: 3
        type: string
      email:
        type: string
      name:
        maxLength: 100
        minLength: 2
        type: string
      phone:
        type: string
      region:
        maxLength: 60
        minLength: 3
        type: string
      zip:
        maxLength: 8
        minLength: 5
        type: string
    required:
    - address
    - city
    - email
    - name
    - phone
    - region
    - zip
    type: object
  models.Item:
    properties:
      brand:
        maxLength: 50
        minLength: 3
        type: string
      chrt_id:
        type: integer
      name:
        maxLength: 100
        minLength: 3
        type: string
      nm_id:
        type: integer
      price:
        type: integer
      rid:
        maxLength: 50
        minLength: 10
        type: string
      sale:
        maximum: 99
        minimum: 0
        type: integer
      size:
        minLength: 1
        type: string
      status:
        type: integer
      total_price:
        type: integer
      track_number:
        maxLength: 50
        minLength: 10
        type: string
    required:
    - brand
    - chrt_id
    - name
    - nm_id
    - price
    - rid
    - size
    - status
    - total_price
    - track_number
    type: object
  models.Order:
    properties:
      customer_id:
        maxLength: 50
        minLength: 2
        type: string
      date_created:
        type: string
      delivery:
        $ref: '#/definitions/models.Delivery'
      delivery_service:
        type: string
      entry:
        maxLength: 10
        minLength: 3
        type: string
      internal_signature:
        type: string
      items:
        items:
          $ref: '#/definitions/models.Item'
        minItems: 1
        type: array
      locale:
        type: string
      oof_shard:
        maxLength: 10
        minLength: 1
        type: string
      order_uid:
        maxLength: 60
        minLength: 10
        type: string
      payment:
        $ref: '#/definitions/models.Payment'
      shardkey:
        maxLength: 10
        minLength: 1
        type: string
      sm_id:
        type: integer
      track_number:
        maxLength: 60
        minLength: 10
        type: string
    required:
    - customer_id
    - date_created
    - delivery
    - delivery_service
    - entry
    - internal_signature
    - items
    - locale
    - oof_shard
    - order_uid
    - payment
    - shardkey
    - sm_id
    - track_number
    type: object
  models.Payment:
    properties:
      amount:
        type: integer
      bank:
        enum:
        - sber
        - alpha
        - vtb
        - tinkoff
        type: string
      currency:
        type: string
      custom_fee:
        maximum: 99
        minimum: 0
        type: integer
      delivery_cost:
        minimum: 0
        type: integer
      goods_total:
        type: integer
      payment_dt:
        type: integer
      provider:
        maxLength: 25
        minLength: 2
        type: string
      request_id:
        type: string
      transaction:
        maxLength: 60
        minLength: 10
        type: string
    required:
    - amount
    - bank
    - currency
    - goods_total
    - payment_dt
    - provider
    - request_id
    - transaction
    type: object
  schemas.ErrorResponse:
    properties:
      error:
        example: error message
        type: string
      success:
        example: false
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: Simple API for wb techschool
  title: Order service API
  version: "1.0"
paths:
  /api/v1/order/{id}:
    get:
      consumes:
      - application/json
      description: returns an order by its order_uid
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.ErrorResponse'
      summary: get order by id
      tags:
      - order
  /ping:
    get:
      consumes:
      - application/json
      description: Returns "pong" if the service is alive
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: health checker
      tags:
      - health
swagger: "2.0"
